project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: "."
preserve_hierarchy: true
files:
  - source: /locales/en.json
    translation: /locales/%two_letters_code%.json
    languages_mapping:
      two_letters_code:
        mrh: mrh
        my: my
